export const SEARCH_IMAGES = "SEARCH_IMAGES";
export const SEARCH_IMAGES_SUCCESS = "SEARCH_IMAGES_SUCCESS";
export const SEARCH_IMAGES_FAILURE = "SEARCH_IMAGES_FAILURE";
export const SELECT_IMAGE = "SELECT_IMAGE";
